// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy.Models;

public partial class PharmacyContext : DbContext
{
    public PharmacyContext()
    {
    }

    public PharmacyContext(DbContextOptions<PharmacyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LoginMaster> LoginMasters { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=SHILLU\\SQLEXPRESS;Initial Catalog=Pharmacy;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LoginMaster>(entity =>
        {
            entity.HasKey(e => e.LoginId);

            entity.ToTable("LoginMaster");

            entity.Property(e => e.LoginId).ValueGeneratedNever();
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.PId);

            entity.Property(e => e.PId)
                .ValueGeneratedNever()
                .HasColumnName("P_Id");
            entity.Property(e => e.PDescription)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("P_Description");
            entity.Property(e => e.PImage)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("P_Image");
            entity.Property(e => e.PName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("P_Name");
            entity.Property(e => e.PPrice).HasColumnName("P_Price");
            entity.Property(e => e.PRackNumber).HasColumnName("P_RackNumber");
            entity.Property(e => e.PStock).HasColumnName("P_Stock");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}