// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pharmacy.Models;

public partial class Product
{
    public int PId { get; set; }

    public string PName { get; set; }

    public byte[] PImage { get; set; }

    public double PPrice { get; set; }

    public string PDescription { get; set; }

    public int PStock { get; set; }

    public int PRackNumber { get; set; }
}